# Homebrew packages
brew "asdf"
brew "bat"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "go"
brew "gh"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "wget"
brew "zoxide"
brew "zsh"

# Cask applications
cask "alt-tab"
cask "bruno"
# cask "cursor"
# cask "docker"
# cask "google-cloud-sdk"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "numi"
cask "obs"
cask "raycast"
cask "rectangle"
cask "stats"
cask "spotify"
cask "visual-studio-code"
